Fluxes_330: Fluxes 330
Fluxes_360: Fluxes 360
Fluxes_390: Fluxes 390
O4_dSCD: O4_fix.SlCol(O4T293K)
O4_dSCD_MAPA: o4_fw352to387nm
Thick_cloud_method: O4
elev_angle: Elev. viewing angle
ignore_elev:
#- -2.0
#- -0.5
#- 0.3
#- 0.5
#- 89.0
#- 0.99
#- 7.0
#- 9.0
#- 14.0
#- 29.0
max_sza: 80
seq: true
sfc_height: 0
site: BREMEN
zenith_elev: 90
